### ISSUE TITLE
ISY not recognizing PLM

### ISSUE THREAD

**Issue by presack** [mrworf/serial-bridge#1]
First off, brilliant project, thank you for doing it!

My ISY is booting into safe mode, not recognizing the PLM. (I am decent with the IT side of things but less confident with the custom wiring.)

The Pi Zero and script seem to be installed and working, and I am getting "Bridging between ttyUSB0 and ttyUSB1".

I have purchased this RJ45 breakout: https://www.amazon.com/gp/product/B07WKKVZRF/ref=ppx_yo_dt_b_asin_title_o06_s01?ie=UTF8&psc=1

And this USB to serial interface: https://www.amazon.com/gp/product/B00IJXZQ7C/ref=ppx_yo_dt_b_asin_title_o06_s02?ie=UTF8&psc=1

I connected things as I understood them from the directions. I have the 2413U USB PLM. I am least confident in the wiring to the USB to serial interface. With the part above, does it look like it needs soldered on? I was hoping for the no solder option. :-) 

I don't expect support here... just trying my best! Dead in the water since my PLM went out and hoping not to start over with a new system. Thanks.

**Comment by mrworf** [comment]
The USB PLM you should be able to just connect to the RPi Zero. But, since you're using the USB to serial adapter (to speak to the ISY994) and a USB PLM, you need also to get a USB Hub, since you won't be able to connect the two otherwise.

So you need the USB serial interface as well as the USB PLM connected at the same time. Something like this https://www.amazon.com/dp/B01JL837X8 and then it should work fine.

**Comment by mrworf** [comment]
Added `--debug` to the options, if you stop the service using `service bridge stop` you can manually invoke the command with `./bridge --debug` and it will show you the data it's sending between the ports. Figured that might be helpful to see that the comms is working.

**Comment by presack** [comment]
Thank you so much for the response. I just unhooked everything so I could photograph it to see if the wiring looks correct. (I think maybe it is not. If I can get mine going, then if it is worthwhile I can add some photos and/or documentation for someone doing this type of setup.
![1](https://user-images.githubusercontent.com/28743902/130333070-acc04f65-7676-460b-b8df-1a90bf539f7d.jpg)
![2](https://user-images.githubusercontent.com/28743902/130333078-e38a1ab1-fe0d-4d8e-9d70-0dcc5f6b2af0.jpg)
![3](https://user-images.githubusercontent.com/28743902/130333080-7413e9a3-c860-45d5-a4e2-bae940c08de8.jpg)
![4](https://user-images.githubusercontent.com/28743902/130333086-8c60f078-afaa-4f2c-935f-a3768a619963.jpg)

**Comment by mrworf** [comment]
Some thoughts...

wiring looks ok, but it's safe to swap RX/TX and see if it makes a difference, nothing should break. 

Did you manage to run the `bridge.py` with the `--debug` argument? If you do and you reboot the ISY, you should see 2 bytes being sent from the ISY after it has booted, it's pinging the PLM. If you don't see any data on either serial port, then swap RX/TX and try again.

I haven't used this particular USB serial converter, but as long as linux sees it, it should work just fine.

Would be great to get the output from bridge.py just to confirm it's seeing two USB serial ports :)

**Comment by presack** [comment]
Thank you again for the response and addition of –debug! I put the new repo on the Pi and was able to run it in debug mode, and it did transfer across a little bit of data like you said (see below). I also tried reversing the rx/tx wires just to see what happened, and by comparison it did not transmit anything. I still get the “Safe Mode” message in Universal Devices Administrator upon reboot (and nothing works) with the “bf 02” transfer and a bridged USB0 and USB1.

I have not yet done anything in the Universal Devices Admin Console, because I figured I am no to that point yet - I think once I have a working PLM I am supposed to do a “Restore Modem/PLM” in the Admin Console… do I need to do that already, or something to “add” the new one?

=======================================================

pi@raspberrypi:~/Downloads/serial-bridge-main $ python3 bridge.py --debug
Debug logging enabled
DEBUG: Found a total of 3 serial ports
INFO: Found ttyAMA0 port
INFO: Found ttyUSB0 port
INFO: Found ttyUSB1 port
INFO: Bridging between ttyUSB0 and ttyUSB1
DEBUG:  /dev/ttyUSB0             | /dev/ttyUSB1                     
DEBUG: -----------------------------------------------------------------------
DEBUG:                         ;          | 20 f1                ;  .      
DEBUG: 15                    ; .        |                         ;         
DEBUG:                         ;          | bf 02 00           ; ...     
DEBUG:                         ;          | 00                    ; .       
DEBUG: 15                    ; .        |                         ;   


=======================================================


I also had one boot up where it did not see USB0 and USB1, so it gave the result below. Not sure why, just putting it here for completeness.

pi@raspberrypi:~/Downloads/serial-bridge-main $ python3 bridge.py --debug
Debug logging enabled
DEBUG: Found a total of 2 serial ports
INFO: Found ttyUSB0 port
INFO: Found ttyAMA0 port
INFO: Bridging between ttyAMA0 and ttyUSB0
DEBUG:  /dev/ttyAMA0             | /dev/ttyUSB0                     
DEBUG: -----------------------------------------------------------------------

**Comment by presack** [comment]
If we are out of ideas and you think a different USB serial converter you have seen work before is worth a try, I am up for ordering one and trying it. In for a penny, in for a pound. :-)

**Comment by mrworf** [comment]
Hmm.. so the RX/TX was correct, that's good. The case where it only saw one USB adapter was odd, if it happens again, please use `dmesg` to dump the kernel boot log so we can see what it saw. It could be that your PLM (if that's the one missing) is already on the fritz. Don't quite trust the wallwart versions 😄 

But the fact that we're seeing some data going in both directions is interesting. The `bf 02 00` stuff would be the ISY I believe, and the PLM should have replied with the same message plus some more bytes. It almost looks like you could be having some power issues, but I assume you have at least 2A power supply. 

If you have another Raspberry Pi with multiple USB ports (such as a RPi2, 3 or 4) you could test this on it using the same SD card but now without the HUB, thus ruling out that one, The bridge.py will work just fine on those devices as well.

**Comment by mrworf** [comment]
(Btw, when sharing the output, please use the code indicator or screenshot since all formatting disappears otherwise)

**Comment by presack** [comment]
![serial-bridge_screenshot](https://user-images.githubusercontent.com/28743902/130379085-a0ba4045-ae59-42c0-9ca8-5c13fb22b6d1.jpg)

I do have a Pi4 I put in place of the Zero. The behavior (attached) was kind of interesting. It would sit happily all day long in debug mode w/ no problems, but once I restart the Isy, the error message in the screenshot would occur. I will drop it below in addition to the screenshot just in case. (I repeated the process and got the same result.)


==========================================================
pi@raspberrypi:~/Downloads/serial-bridge-main $ python3 bridge.py --debug
Debug logging enabled
DEBUG: Found a total of 3 serial ports
INFO: Found ttyAMA0 port
INFO: Found ttyUSB0 port
INFO: Found ttyUSB1 port
INFO: Bridging between ttyUSB0 and ttyUSB1
DEBUG:  /dev/ttyUSB0                      | /dev/ttyUSB1                     
DEBUG: -----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bridge.py", line 109, in <module>
    srcdata = splitdata(transfer_data(src, dst))
  File "bridge.py", line 56, in transfer_data
    data = a.read(a.in_waiting)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

**Comment by mrworf** [comment]
That was unexpected. Most likely some package woke up on the RPi4 and snagged the serial port. Didn't see that one coming. You could try to find out what, by installing `lsof` (`apt install lsof`) and then issue (as root) `lsof | grep ttyUSB` and see which software is actively using the USB serial port.

**Comment by presack** [comment]
Hmmmm, it looks like the script has control:
pi@raspberrypi:~/Downloads/serial-bridge-main $ sudo lsof | grep ttyUSB
python3   443                           root    3u      CHR      188,0      0t0        327 /dev/ttyUSB0
python3   443                           root    8u      CHR      188,1      0t0        329 /dev/ttyUSB1

I did try switching the USB ports on the pi4 just to mix it up... basically the same result as last time, except this time it showed the transfer of the bf 02 sequence before throwing the error (as attached).

![serial_bridge_screenshot2](https://user-images.githubusercontent.com/28743902/130383485-7019437c-3252-46d6-87cd-cc62f7f9f8e4.jpg)

**Comment by presack** [comment]
Meant to mention this earlier: I had configured mine to run without the desktop environment. That should be fine, right? I would assume so, but I am just trying to think of anything I could have done that could be a problem.

**Comment by mrworf** [comment]
yes, that shouldn't make any difference. In fact, running in non-desktop is preferred
